### ISSUE TITLE
Delete this repo?

### ISSUE THREAD

**Issue by jeddy3** [stylelint/postcss-stylelint-reporter#1]
@davidtheclark Can we delete this repo now, or is there still plans to build a reporter that works with both simple PostCSS warnings and those enhanced by stylelint?

**Comment by ntwb** [comment]
FWIW, I started on `grunt-stylelint` last night:

<img width="756" alt="grunt-stylelint" src="https://cloud.githubusercontent.com/assets/1016458/15008331/ec593e5a-1222-11e6-84c3-79881e91a361.png">

Regardless of what the screenshot might or might not infer, it's pretty hacky, and doesn't actually report anything yet, so is very much a work in progress, with some luck by the end of this weekend it will actually work though 😄

So, to come back to this actual GitHub issue at hand, with the Gulp/Grunt stylelint plugins the current thought process is to expose stylelint's included reporters for now isn't it? Likewise for formatters?

**Comment by davidtheclark** [comment]
@jeddy3 Yes, we can delete this repo.

@ntwb Yes, that's the plan. Great that you're working on a grunt plugin that uses the same reporters stylelint itself can use!
